[tools]
aws-cli = "latest"
"cargo:nippo" = "latest"
claude = "latest"
ecspresso = "latest"
fzf = "latest"
gcloud = "latest"
gh = "latest"
ghq = "latest"
jq = "latest"
node = "latest"
ruby = "latest"
starship = "latest"
terraform = "latest"
uv = "latest"
