[settings]
minimum_release_age = "3d"

[tools]
aws-cli = "latest"
bun = "latest"
"cargo:nippo" = "latest"
claude = "latest"
ecspresso = "latest"
fzf = "latest"
gcloud = "latest"
gh = "latest"
ghq = "latest"
jq = "latest"
node = "latest"
ollama = "latest"
python = "latest"
ruby = "latest"
rust = "latest"
starship = "latest"
terraform = "latest"
uv = "latest"
